#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1


reload_service()
{
        stop "$@"
        sleep 5
        start "$@"
}

start_service()
{
        if [ $(uci get speedifyconf.Setup.enabled) == 1 ]
         then
                uci set tinyvpnconf.Setup.enabled=0
                uci set engardeconf.Setup.enabled=0
                uci commit tinyvpnconf
                uci commit engardeconf
                cp /usr/lib/lua/luci/view/admin_status/index.htm.speedify /usr/lib/lua/luci/view/admin_status/index.htm
                continue
        else
                exit 0
        fi

        /etc/init.d/tinyvpnconf stop
        /etc/init.d/engardeconf stop
        procd_open_instance
        procd_set_param command sh /usr/lib/speedifyconf/run.sh start  > /usr/lib/speedifyconf/speedifyconfig.log
        procd_close_instance
}

stop_service()
{
        /usr/bin/killall speedify
}