#Author: TALMASH

include $(TOPDIR)/rules.mk
PKG_NAME:=luci-app-wifibasic
LUCI_Title:=Simplified WiFi configuration
LUCI_PKGARCH:=all
LUCI_DEPENDS:= +libuci
PKG_VERSION:=0.1
PKG_RELEASE:=0.1

PKG_MAINTANINER:=TALMASH
PKG_LICENSE:=BSD
PKG_LICENSE_FILES:=LICENSE


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
