#Author: TALMASH

include $(TOPDIR)/rules.mk
PKG_NAME:=luci-app-ntopngconfig
LUCI_Title:=Ntopng Configuration (SmoothWAN)
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+libuci
PKG_VERSION:=1.0
PKG_RELEASE:=1.0

PKG_MAINTANINER:=TALMASH
PKG_LICENSE:=BSD
PKG_LICENSE_FILES:=LICENSE


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
