#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

service_triggers()
{
        procd_add_reload_trigger "tinyvpnconf"
}

reload_service()
{
        stop "$@"
        sleep 5
        start "$@"
}

start_service()
{
        if [ $(uci get tinyvpnconf.Setup.enabled) == 1 ]
         then
                uci set speedifyconf.Setup.enabled=0
                uci set engardeconf.Setup.enabled=0
                uci commit speedifyconf
                uci commit tinyvpnconf
                cp /usr/lib/lua/luci/view/admin_status/index.htm.orig /usr/lib/lua/luci/view/admin_status/index.htm
                continue
        else
                exit 0
        fi

        /etc/init.d/speedifyconf restart
        /etc/init.d/engardeconf restart
        dstAddr=$(uci get tinyvpnconf.Setup.dstAddr):$(uci get tinyvpnconf.Setup.dstPort)
        password=$(uci get tinyvpnconf.Setup.pass)
        fecparam=$(uci get tinyvpnconf.Setup.fecParam)
        subnet=$(uci get tinyvpnconf.Setup.subnet)

        if [ ! "$(uci show network.TinyFEC)" ]; then
          uci set network.TinyFEC=interface
          uci set network.TinyFEC.proto='static'
          uci set network.TinyFEC.device='tinyfec0'
          uci set network.TinyFEC.ipaddr='10.202.0.2'
          uci set network.TinyFEC.netmask='255.255.255.0'
          uci set network.TinyFEC.gateway='10.202.0.1'
          uci add_list firewall.cfg03dc81.network='TinyFEC'
          uci commit firewall
          uci commit network
          ifup TinyFEC
        fi
        ip route add $(uci get tinyvpnconf.Setup.dstAddr)/32 via $(ip route | awk 'NR==1{print $3}')
        screen -L -Logfile /tmp/tinyfecvpn.log -d -m sh -c "ulimit -n 65535 && nice -n -20 /usr/bin/tinyfecvpn -c -r$dstAddr -f$fecparam -k $password --sub-net $subnet --keep-reconnect --tun-mtu 65535 --disable-checksum --disable-obscure --tun-dev tinyfec0"
}

stop_service()
{
        killall tinyfecvpn
        ip route del $(uci get tinyvpnconf.Setup.dstAddr)/32
        if [ "$(uci show network.TinyFEC)" ]; then
           uci del_list firewall.cfg03dc81.network='TinyFEC'
           uci del network.TinyFEC
           uci commit firewall
           uci commit network
        fi
}