#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

service_triggers()
{
        procd_add_reload_trigger "tinyvpnconf"
}

reload_service()
{
        stop "$@"
        sleep 5
        start "$@"
}

start_service()
{
        if [ $(uci get tinyvpnconf.Setup.enabled) == 1 ]
         then
                uci set speedifyconf.Setup.enabled=0
                uci set engardeconf.Setup.enabled=0
                uci commit speedifyconf
                uci commit engardeconf
                cp /usr/lib/lua/luci/view/admin_status/index.htm.tinyfec /usr/lib/lua/luci/view/admin_status/index.htm
                continue
        else
                stop "$@"
                exit 0
        fi

        /etc/init.d/speedifyconf stop
        /etc/init.d/engardeconf stop
        sleep 10
        dstAddr=$(uci get tinyvpnconf.Setup.dstAddr):$(uci get tinyvpnconf.Setup.dstPort)
        password=$(uci get tinyvpnconf.Setup.pass)
        fecparam=$(uci get tinyvpnconf.Setup.fecParam)
        subnet=$(uci get tinyvpnconf.Setup.subnet)

        uci del network.wan
        uci set network.wan=interface
        uci set network.wan.proto='static'
        uci set network.wan.device='tinyfec0'
        uci set network.wan.ipaddr='10.202.0.2'
        uci set network.wan.netmask='255.255.255.0'
        uci set network.wan.gateway='10.202.0.1'
        uci del_list firewall.cfg03dc81.network='wan'
        uci add_list firewall.cfg03dc81.network='wan'
        uci commit firewall
        uci commit network
        ifup wan
        ip route del $(uci get tinyvpnconf.Setup.dstAddr)/32
        ip route add $(uci get tinyvpnconf.Setup.dstAddr)/32 via $(ip route | awk 'NR==1{print $3}')
        screen -L -Logfile /tmp/tinyfecvpn.log -d -m sh -c "ulimit -n 65535 && nice -n -20 /usr/bin/tinyfecvpn -c -r$dstAddr -f$fecparam -k $password --sub-net $subnet --keep-reconnect --tun-mtu 65535 --disable-checksum --disable-obscure --tun-dev tinyfec0"
        uci set upnpd.config.external_ip=$(uci get tinyvpnconf.Setup.dstAddr)
        uci set upnpd.config.enabled='1'
        uci commit upnpd
        service miniupnpd restart
        ip route add default via 10.202.0.1
}

stop_service()
{
        killall tinyfecvpn
}