#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

service_triggers()
{
        procd_add_reload_trigger "engardeconf"
}

reload_service()
{
        stop "$@"
        sleep 5
        start "$@"
}

start_service()
{
        if [ $(uci get engardeconf.Setup.enabled) == 1 ]
         then
                uci set speedifyconf.Setup.enabled=0
                uci set tinyvpnconf.Setup.enabled=0
                uci commit speedifyconf
                uci commit tinyvpnconf
                cp /usr/lib/lua/luci/view/admin_status/index.htm.engarde /usr/lib/lua/luci/view/admin_status/index.htm
                continue
        else
                stop "$@"
                exit 0
        fi
        /etc/init.d/speedifyconf stop
        /etc/init.d/tinyvpnconf stop
        sleep 10
        listenAddr=$(uci get engardeconf.Setup.listenAddr):$(uci get engardeconf.Setup.listenPort)
        dstAddr=$(uci get engardeconf.Setup.dstAddr):$(uci get engardeconf.Setup.dstPort)
        skey=$(printf $(uci get engardeconf.Setup.pass) | openssl dgst -binary -sha256 | openssl base64 -A)
        spubkey=$(echo $skey | wg pubkey)
        ckey=$(printf $skey | openssl dgst -binary -sha256 | openssl base64 -A)
        cpubkey=$(echo $ckey | wg pubkey)
        psk=$(printf $ckey | openssl dgst -binary -sha256 | openssl base64 -A)
        mkdir /etc/engarde
        echo -e 'client:\n listenAddr: '$listenAddr' \n dstAddr: '$dstAddr' \n excludedInterfaces: \n   - "br-lan"\n   - "wan"\n webManager:\n     listenAddr: 0.0.0.0:9001\n' > /etc/engarde/engarde.yml
        uci del_list firewall.cfg03dc81.network='wan'
        uci add_list firewall.cfg03dc81.network='wan'
        uci del network.wan
        uci del network.wan6
        uci set network.wan=interface
        uci set network.wan.proto='wireguard'
        uci del network wireguard_wan # =cfg115a64
        uci add network wireguard_wan # =cfg115a64
        uci set network.wan.private_key="$ckey"
        uci add_list network.wan.addresses='10.202.0.10'
        uci set network.wan.mtu='1280'
        uci set network.@wireguard_wan[-1].public_key="$spubkey"
        uci set network.@wireguard_wan[-1].preshared_key="$psk"
        uci add_list network.@wireguard_wan[-1].allowed_ips='0.0.0.0/0'
        uci set network.@wireguard_wan[-1].route_allowed_ips='1'
        uci set network.@wireguard_wan[-1].endpoint_host="$(uci get engardeconf.Setup.listenAddr)"
        uci set network.@wireguard_wan[-1].endpoint_port="$(uci get engardeconf.Setup.listenPort)"
        uci set network.@wireguard_wan[-1].persistent_keepalive='25'
        uci commit firewall
        uci commit network
        ifup wan
        screen -L -Logfile /tmp/engarde.log -d -m sh -c "ulimit -n 65535 && nice -n -20 /usr/bin/engarde-client /etc/engarde/engarde.yml"
        uci set upnpd.config.external_ip=$(uci get engardeconf.Setup.dstAddr)
        uci set upnpd.config.enabled='1'
        uci commit upnpd
        /etc/init.d/miniupnpd restart
}

stop_service()
{
        killall engarde-client
}