#Author: TALMASH

include $(TOPDIR)/rules.mk
PKG_NAME:=luci-app-piholeconf
LUCI_Title:=Pihole Setup and Configuration
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+piholeconf +libuci
PKG_VERSION:=1.1
PKG_RELEASE:=1.1

PKG_MAINTANINER:=TALMASH
PKG_LICENSE:=BSD
PKG_LICENSE_FILES:=LICENSE


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
